import os
import json
import requests
from flask import Flask, render_template, request, jsonify
from dotenv import load_dotenv
from core.analyzer import CodeAnalyzer

load_dotenv()

app = Flask(__name__)

# ─── Config ───
MIMO_API_KEY = os.getenv("MIMO_API_KEY", "")
MIMO_API_URL = os.getenv("MIMO_API_URL", "https://api.xiaomimimo.com/v1")
UPLOAD_FOLDER = "/tmp/uploads"
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

# Initialize analyzer
analyzer = CodeAnalyzer()

def call_mimo_ai(prompt: str, context: dict) -> str:
    """Call MiMo AI with project context for documentation generation"""
    if not MIMO_API_KEY:
        return _demo_response(context)
    
    system_prompt = """You are MiMo Doc Writer, an expert technical documentation generator.
You analyze codebases and create comprehensive, well-structured documentation.

Your documentation style:
1. Start with a clear project overview
2. Explain the architecture and design decisions
3. Document each component with WHY it exists (not just what)
4. Include usage examples
5. Highlight important patterns and conventions

Always structure your output in Markdown format.
Focus on explaining the reasoning behind code, not just describing it."""

    headers = {
        "Authorization": f"Bearer {MIMO_API_KEY}",
        "Content-Type": "application/json"
    }
    
    payload = {
        "model": "MiMo-V2.5",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"{prompt}\n\nProject Context:\n{json.dumps(context, indent=2)}"}
        ],
        "temperature": 0.3,
        "max_tokens": 4096
    }
    
    try:
        response = requests.post(
            f"{MIMO_API_URL}/chat/completions",
            headers=headers,
            json=payload,
            timeout=120
        )
        response.raise_for_status()
        result = response.json()
        return result["choices"][0]["message"]["content"]
    except Exception as e:
        return f"# Error\n\nFailed to generate documentation: {str(e)}"

def _demo_response(context: dict) -> str:
    """Demo response when no API key"""
    project_name = context.get("project_name", "Unknown")
    scan = context.get("scan", {})
    understand = context.get("understand", {})
    
    return f"""# {project_name} Documentation

## Overview
This project is a codebase with **{scan.get('total_files', 0)}** files.

## Technology Stack
{_format_languages(scan.get('languages', {}))}

## Architecture

### Components
{_format_classes(understand.get('classes', []))}

### Key Functions
{_format_functions(understand.get('functions', [])[:10])}

### Dependencies
{_format_deps(understand.get('dependencies', []))}

## File Structure
The project follows a standard structure with main entry point at `{context.get('main_file', 'main.py')}`.

---
*Documentation generated by MiMo Doc Writer*
"""

def _format_languages(langs: dict) -> str:
    return "\n".join([f"- **{lang}**: {count} files" for lang, count in langs.items()])

def _format_classes(classes: list) -> str:
    if not classes:
        return "- No classes detected"
    return "\n".join([f"- `{c['name']}`" + (f" extends `{c['parent']}`" if c.get('parent') else "") for c in classes[:10]])

def _format_functions(funcs: list) -> str:
    if not funcs:
        return "- No functions detected"
    return "\n".join([f"- `{f['name']}()` - {f['file']}" for f in funcs])

def _format_deps(deps: list) -> str:
    if not deps:
        return "- No external dependencies"
    return "\n".join([f"- `{d}`" for d in deps[:15]])

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/api/analyze", methods=["POST"])
def analyze():
    """Full analysis pipeline: SCAN → UNDERSTAND → GENERATE"""
    try:
        # Handle file upload or GitHub URL
        if 'files' in request.files:
            # File upload mode
            files = request.files.getlist('files')
            project_path = _save_uploaded_files(files)
            doc_type = request.form.get('doc_type', 'full')
        elif request.is_json and request.json.get('github_url'):
            # GitHub clone mode
            project_path = _clone_github(request.json['github_url'])
            doc_type = request.json.get('doc_type', 'full')
        else:
            return jsonify({"error": "No files or GitHub URL provided"}), 400
        
        if not project_path:
            return jsonify({"error": "Failed to process input"}), 400
        
        # STEP 1: SCAN & STEP 2: UNDERSTAND
        context = analyzer.prepare_for_ai(project_path)
        
        # STEP 3: GENERATE documentation
        prompt = _get_prompt(doc_type)
        documentation = call_mimo_ai(prompt, context)
        
        return jsonify({
            "documentation": documentation,
            "analysis": {
                "files_scanned": context["scan"]["total_files"],
                "languages": context["scan"]["languages"],
                "classes_found": len(context["understand"]["classes"]),
                "functions_found": len(context["understand"]["functions"]),
                "dependencies": context["understand"]["dependencies"]
            }
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

def _save_uploaded_files(files) -> str:
    """Save uploaded files to temp directory"""
    import tempfile
    import zipfile
    
    temp_dir = tempfile.mkdtemp(dir=UPLOAD_FOLDER)
    
    for file in files:
        if file.filename.endswith('.zip'):
            zip_path = os.path.join(temp_dir, 'upload.zip')
            file.save(zip_path)
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall(temp_dir)
            os.remove(zip_path)
        else:
            filepath = os.path.join(temp_dir, file.filename)
            os.makedirs(os.path.dirname(filepath), exist_ok=True)
            file.save(filepath)
    
    return temp_dir

def _clone_github(url: str) -> str:
    """Clone GitHub repository"""
    import subprocess
    import tempfile
    
    temp_dir = tempfile.mkdtemp(dir=UPLOAD_FOLDER)
    result = subprocess.run(
        ["git", "clone", "--depth=1", url, temp_dir],
        capture_output=True, text=True, timeout=60
    )
    
    return temp_dir if result.returncode == 0 else None

def _get_prompt(doc_type: str) -> str:
    """Get documentation prompt based on type"""
    prompts = {
        "full": "Generate comprehensive documentation for this project. Include overview, architecture, API reference, usage examples, and development guide.",
        "readme": "Generate a professional README.md with badges, installation, usage, and contributing guidelines.",
        "api": "Focus on API documentation. Document all public functions, classes, methods with parameters, return values, and examples.",
        "architecture": "Focus on architecture documentation. Explain the design patterns, component relationships, data flow, and key decisions."
    }
    return prompts.get(doc_type, prompts["full"])

if __name__ == "__main__":
    port = int(os.getenv("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=True)
